/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-03 13:21:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class BMI_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>BMI Calculator</title>\r\n");
      out.write("      <style>\r\n");
      out.write("    @import url(\"https://fonts.googleapis.com/css2?family=Nunito:wght@600;700;800;900&display=swap\");\r\n");
      out.write("* {\r\n");
      out.write("  padding: 0;\r\n");
      out.write("  margin: 0;\r\n");
      out.write("  box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("  min-height: 20vh;\r\n");
      out.write("  background: linear-gradient(to right, #0bb288, #dcdcdc);\r\n");
      out.write("  font-family: \"Nunito\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write(".container {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  transform: translate(-50%, -50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box {\r\n");
      out.write("  min-width: 600px;\r\n");
      out.write("  min-height: 600px;\r\n");
      out.write("  background: rgb(250, 250, 250);\r\n");
      out.write("  border-radius: 38px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  margin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write(".box::before {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  height: 110%;\r\n");
      out.write("  width: 110%;\r\n");
      out.write("  left: -5%;\r\n");
      out.write("  top: -5%;\r\n");
      out.write("  background-color: rgba(255, 255, 255, 0.3);\r\n");
      out.write("  box-shadow: 0px 0px 166px -31px rgba(0, 0, 0, 0.15);\r\n");
      out.write("  border-radius: 60px;\r\n");
      out.write("  z-index: -1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      h1 {\r\n");
      out.write("        color: #0bb288;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 36px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      /* Add a transition effect */\r\n");
      out.write("      input[type=\"number\"] {\r\n");
      out.write("        transition: all 0.5s ease-out;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        border: 1px solid #0bb288;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      input[type=\"number\"]:focus {\r\n");
      out.write("        outline: none;\r\n");
      out.write("        box-shadow: 0 0 10px #0bb288;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      select {\r\n");
      out.write("        transition: all 0.5s ease-out;\r\n");
      out.write("        width: 300px;\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        border: 1px solid #0bb288;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      select:focus {\r\n");
      out.write("        outline: none;\r\n");
      out.write("        box-shadow: 0 0 10px #0bb288;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      input[type=\"reset\"],\r\n");
      out.write("      input[type=\"submit\"] {\r\n");
      out.write("        transition: all 0.5s ease-out;\r\n");
      out.write("        background-color: #0bb288;\r\n");
      out.write("        color: white;\r\n");
      out.write("        padding: 10px 20px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      input[type=\"reset\"]:hover,\r\n");
      out.write("      input[type=\"submit\"]:hover {\r\n");
      out.write("        background-color: white;\r\n");
      out.write("        color: #0bb288;\r\n");
      out.write("        box-shadow: 0 0 10px #0bb288;\r\n");
      out.write("      }\r\n");
      out.write("      #progress-bar {\r\n");
      out.write("  width: 50%;\r\n");
      out.write("  height: 20px;\r\n");
      out.write("  background-color: rgb(230, 230, 230);\r\n");
      out.write("  border-radius: 25px;\r\n");
      out.write("  margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#progress {\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  background-color: #a16d63;\r\n");
      out.write("  border-radius: 25px;\r\n");
      out.write("  transition: width 0.75s linear;\r\n");
      out.write("}\r\n");
      out.write(" .dot {\r\n");
      out.write("    width: 10px;\r\n");
      out.write("    height: 10px;\r\n");
      out.write("    background-color: #0bb288;\r\n");
      out.write("    border-radius: 50%;\r\n");
      out.write("    position: absolute;\r\n");
      out.write("  }\r\n");
      out.write("  .dot1 {\r\n");
      out.write("    top: 30px;\r\n");
      out.write("    left: 30px;\r\n");
      out.write("  }\r\n");
      out.write("  .dot2 {\r\n");
      out.write("    bottom: 30px;\r\n");
      out.write("    right: 30px;\r\n");
      out.write("    top: 30px;\r\n");
      out.write("  }\r\n");
      out.write("  .dot3 {\r\n");
      out.write("    bottom: 30px;\r\n");
      out.write("    right: 30px;\r\n");
      out.write("  }\r\n");
      out.write("  .dot4 {\r\n");
      out.write("    bottom: 30px;\r\n");
      out.write("    left: 30px;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  a:hover{\r\n");
      out.write("    color: #0bb288;\r\n");
      out.write("    box-shadow: 1px 1px 10px rgb(214, 210, 210);\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"box\">\r\n");
      out.write("        <div class=\"dot dot1\"></div>\r\n");
      out.write("          <div class=\"dot dot2\"></div>\r\n");
      out.write("             <div class=\"dot dot3\"></div>\r\n");
      out.write("               <div class=\"dot dot4\"></div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <h1>BMI Calculator</h1>\r\n");
      out.write("        <p style=\"text-align: center; margin-bottom: 20px;\"><a target=\"_blank\" style=\"text-decoration: none; font-size: 20px; color:#a16d63 !important;\" href=\"https://www.rapidtables.com/convert/length/feet-to-cm.html\">For unit converter-> click here</a></p>\r\n");
      out.write("        <div id=\"progress-bar\">\r\n");
      out.write("    <div id=\"progress\"></div></div>\r\n");
      out.write("\r\n");
      out.write("        <br>\r\n");
      out.write("        <form id=\"bmi-form\" action=\"#\">\r\n");
      out.write("          <p>\r\n");
      out.write("            <label for=\"weight\">Weight (kg):</label>\r\n");
      out.write("            <input style=\"border-radius: 16px;\" type=\"number\" id=\"weight\" name=\"weight\" min=\"30\" max=\"200\" step=\".01\" required oninput=\"completeTask()\">\r\n");
      out.write("            <span class=\"error\" id=\"weight-error\"></span>\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <label for=\"height\">Height (cm):</label>\r\n");
      out.write("            <input style=\"border-radius: 16px;\" type=\"number\" id=\"height\" min=\"60\" max=\"250\" step=\".01\" required oninput=\"completeTask()\">\r\n");
      out.write("            <span class=\"error\" id=\"height-error\"></span>\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <label for=\"age\">Age (years):</label>\r\n");
      out.write("            <input style=\"border-radius: 16px;\" type=\"number\" id=\"age\" name=\"age\" min=\"1\" max=\"120\" required oninput=\"completeTask()\">\r\n");
      out.write("            <span class=\"error\" id=\"age-error\"></span>\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <label for=\"gender\">Gender:</label>\r\n");
      out.write("            <select style=\"border-radius: 16px; margin-left: 30px;\" id=\"gender\" name=\"gender\" required oninput=\"completeTask()\">\r\n");
      out.write("              <option value=\"\" selected>Select Gender</option>\r\n");
      out.write("              <option value=\"male\">Male</option>\r\n");
      out.write("              <option value=\"female\">Female</option>\r\n");
      out.write("            </select>\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <label for=\"activity-level\">Activity: </label>\r\n");
      out.write("            <select style=\"border-radius: 16px; margin-left: 30px;\" id=\"activity-level\" name=\"activity-level\" required oninput=\"completeTask()\">\r\n");
      out.write("              <option value=\"\" selected>Select Activity Level</option>\r\n");
      out.write("              <option value=\"sedentary\">Sedentary (little or no exercise)</option>\r\n");
      out.write("              <option value=\"lightly-active\">Lightly Active (light exercise 1-3 days/week)</option>\r\n");
      out.write("              <option value=\"moderately-active\">Moderately Active (moderate exercise 3-5 days/week)</option>\r\n");
      out.write("              <option value=\"very-active\">Very Active (hard exercise 6-7 days/week)</option>\r\n");
      out.write("              <option value=\"extra-active\">Extra Active (very hard exercise, physical job, or training twice a day)</option>\r\n");
      out.write("            </select>\r\n");
      out.write("          </p>\r\n");
      out.write("          <br>\r\n");
      out.write("          <p>\r\n");
      out.write("            <input type=\"reset\" value=\"Reset\">\r\n");
      out.write("            <input type=\"submit\" value=\"Calculate BMI\" onclick=\"calculateBMI()\">\r\n");
      out.write("          </p>\r\n");
      out.write("        </form> \r\n");
      out.write("        <button id=\"hidden-button\" style=\"display: none\" onclick=\"completeTask()\">Complete Task</button>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div id=\"result\"></div>\r\n");
      out.write("        <br>\r\n");
      out.write("        <div id=\"calorie-result\">  \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script> \r\n");
      out.write("      const inputWeight = document.getElementById(\"weight\");\r\n");
      out.write("inputWeight.addEventListener(\"input\", function(e) {\r\n");
      out.write("  if (!/^\\d{0,5}(\\.\\d{0,2})?$/.test(e.target.value)) {\r\n");
      out.write("    e.target.value = e.target.value.slice(0, -1);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("   if (this.value.match(/^(3[0-9]|[4-9][0-9]|[1-9][0-9][0-9]|200)(\\.[0-9]{1,2})?$/)) {\r\n");
      out.write("    document.getElementById(\"result\").innerHTML = \"\";\r\n");
      out.write("  }\r\n");
      out.write("  if (!this.value.match(/^(3[0-9]|[4-9][0-9]|[1-9][0-9][0-9]|200)(\\.[0-9]{1,2})?$/)) {\r\n");
      out.write("    this.setCustomValidity(\"weight should be between 30 kg and 200 kg\");\r\n");
      out.write("  } else {\r\n");
      out.write("    this.setCustomValidity(\"\");\r\n");
      out.write("  }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("const inputHeight = document.getElementById(\"height\");\r\n");
      out.write("inputHeight.addEventListener(\"input\", function(e) {\r\n");
      out.write("  if (!/^\\d{0,5}(\\.\\d{0,2})?$/.test(e.target.value)) {\r\n");
      out.write("e.target.value = e.target.value.slice(0, -1);\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  if (this.value.match(/^(6[0-9]|[7-9][0-9]|[1-9][0-9][0-9]|2[0-4][0-9][0-9]|250)(.[0-9]{1,2})?$/)) {\r\n");
      out.write("    document.getElementById(\"result\").innerHTML = \"\";\r\n");
      out.write("  }\r\n");
      out.write("  if (!this.value.match(/^(6[0-9]|[7-9][0-9]|[1-9][0-9][0-9]|2[0-4][0-9][0-9]|250)(.[0-9]{1,2})?$/)) {\r\n");
      out.write("    this.setCustomValidity(\"height should be between 60 cm and 250 cm\");\r\n");
      out.write("  } else {\r\n");
      out.write("    this.setCustomValidity(\"\");\r\n");
      out.write("  }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("const inputAge = document.getElementById(\"age\");\r\n");
      out.write("inputAge.addEventListener(\"input\", function(e) {\r\n");
      out.write("  if (!/^\\d{0,3}(\\.\\d{0,1})?$/.test(e.target.value)) {\r\n");
      out.write("    e.target.value = e.target.value.slice(0, -1);\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  var age = document.getElementById(\"age\").value;\r\n");
      out.write("  if (/^\\d{0,3}(\\.\\d{0,1})?$/.test(age) && age >= 1 && age <= 120) {\r\n");
      out.write("    document.getElementById(\"result\").innerHTML = \"\";\r\n");
      out.write("  }\r\n");
      out.write("  if (!/^\\d{0,3}(\\.\\d{0,1})?$/.test(age) || age < 1 || age > 120) {\r\n");
      out.write("    this.setCustomValidity(\"Invalid age. Age must be a whole number between 1 and 120\");\r\n");
      out.write("  } else {\r\n");
      out.write("    this.setCustomValidity(\"\");\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  if (age % 1 !== 0) {\r\n");
      out.write("    if (age % 1 >= 0.1 && age % 1 < 0.6) {\r\n");
      out.write("      age = Math.floor(age);\r\n");
      out.write("    } else {\r\n");
      out.write("      age = Math.ceil(age);\r\n");
      out.write("    }\r\n");
      out.write("    document.getElementById(\"age\").value = age;\r\n");
      out.write("  }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write(" function preventSpecialChar(event) {\r\n");
      out.write("  if (event.which != 8 && event.which != 0 && (event.which < 48 || event.which > 57) && event.which !== 46) {\r\n");
      out.write("    event.preventDefault();\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("document.getElementById(\"weight\").addEventListener(\"keypress\", preventSpecialChar);\r\n");
      out.write("document.getElementById(\"height\").addEventListener(\"keypress\", preventSpecialChar);\r\n");
      out.write("document.getElementById(\"age\").addEventListener(\"keypress\", preventSpecialChar);\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"bmi-form\").addEventListener(\"submit\", function(event) {\r\n");
      out.write("  event.preventDefault();\r\n");
      out.write("  document.querySelector(\".box\").style.minHeight = \"600px\";\r\n");
      out.write("});\r\n");
      out.write("document.addEventListener(\"keyup\", function(event) {\r\n");
      out.write("  if (event.key === \"Enter\") {\r\n");
      out.write("    calculateBMI();\r\n");
      out.write("  }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write(" function calculateBMI() {\r\n");
      out.write("   // Get the inputs\r\n");
      out.write("   var weight = document.getElementById(\"weight\").value;\r\n");
      out.write("   var height = document.getElementById(\"height\").value;\r\n");
      out.write("   var age = document.getElementById(\"age\").value;\r\n");
      out.write("\r\n");
      out.write("   if (weight < 30 || weight > 200) {\r\n");
      out.write("    document.getElementById(\"result\").innerHTML = \"Error: Invalid weight entered\";\r\n");
      out.write("    return;\r\n");
      out.write("   }\r\n");
      out.write("   if (height < 60 || height > 250) {\r\n");
      out.write("    document.getElementById(\"result\").innerHTML = \"Error: Invalid height entered\";\r\n");
      out.write("    return;\r\n");
      out.write("   }\r\n");
      out.write("   if (age < 1 || age > 120) {\r\n");
      out.write("    document.getElementById(\"result\").innerHTML = \"Error: Invalid age entered\";\r\n");
      out.write("    return;\r\n");
      out.write("  }\r\n");
      out.write("   if (!weight || !height || !age) {\r\n");
      out.write("    document.getElementById(\"result\").innerHTML = \"Error: Please enter weight, height, and age.\";\r\n");
      out.write("    return;\r\n");
      out.write("   }\r\n");
      out.write("    var gender = document.getElementById(\"gender\").value;\r\n");
      out.write("    var activityLevel = document.getElementById(\"activity-level\").value;\r\n");
      out.write("\r\n");
      out.write("    // Calculate the BMI\r\n");
      out.write("    var bmi = weight / ((height / 100) * (height / 100));\r\n");
      out.write("\r\n");
      out.write("    // Determine the user's BMR based on gender and age\r\n");
      out.write("    var bmr;\r\n");
      out.write("    if (gender === \"male\") {\r\n");
      out.write("      bmr = 66.47 + (13.75 * weight) + (5.003 * height) - (6.755 * age);\r\n");
      out.write("    } else if (gender === \"female\") {\r\n");
      out.write("      bmr = 655.1 + (9.563 * weight) + (1.850 * height) - (4.676 * age);\r\n");
      out.write("    } else {\r\n");
      out.write("      // Error: gender not selected\r\n");
      out.write("      document.getElementById(\"result\").innerHTML = \"Error: Gender not selected\";\r\n");
      out.write("       return;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // Determine the user's daily calorie needs based on activity level\r\n");
      out.write("      var calorieNeeds;\r\n");
      out.write("      switch (activityLevel) {\r\n");
      out.write("        case \"sedentary\":\r\n");
      out.write("          calorieNeeds = bmr * 1.2;\r\n");
      out.write("          break;\r\n");
      out.write("        case \"lightly-active\":\r\n");
      out.write("          calorieNeeds = bmr * 1.375;\r\n");
      out.write("          break;\r\n");
      out.write("        case \"moderately-active\":\r\n");
      out.write("          calorieNeeds = bmr * 1.55;\r\n");
      out.write("          break;\r\n");
      out.write("        case \"very-active\":\r\n");
      out.write("            calorieNeeds = bmr * 1.725;\r\n");
      out.write("          break;\r\n");
      out.write("        case \"extra-active\":\r\n");
      out.write("          calorieNeeds = bmr * 1.9;\r\n");
      out.write("          break;\r\n");
      out.write("        default:\r\n");
      out.write("          // Error: activity level not selected\r\n");
      out.write("          document.getElementById(\"result\").innerHTML = \"Error: Activity level not selected\";\r\n");
      out.write("          return;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("        // Determine the user's BMI category based on their BMI\r\n");
      out.write("        var bmiCategory;\r\n");
      out.write("        if (bmi < 18.5) {\r\n");
      out.write("          bmiCategory = \"Underweight\";\r\n");
      out.write("        } else if (bmi >= 18.5 && bmi < 25) {\r\n");
      out.write("          bmiCategory = \"Normal weight\";\r\n");
      out.write("        } else if (bmi >= 25 && bmi < 30) {\r\n");
      out.write("          bmiCategory = \"Overweight\";\r\n");
      out.write("        } else {\r\n");
      out.write("          bmiCategory = \"Obese\";\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Output the BMI and description\r\n");
      out.write("        document.getElementById(\"result\").innerHTML = \"Your BMI is \" + bmi.toFixed(2) + \" and you are \" + bmiCategory + \".\";\r\n");
      out.write("        document.getElementById(\"calorie-result\").innerHTML = \"You need \" + calorieNeeds.toFixed(1) + \" calories per day.\";\r\n");
      out.write("      };\r\n");
      out.write("const progressBar = document.querySelector(\"#progress\");\r\n");
      out.write("let taskCounter = 0;\r\n");
      out.write("let weightCounter = 0;\r\n");
      out.write("let heightCounter = 0;\r\n");
      out.write("let ageCounter = 0;\r\n");
      out.write("let genderCounter = 0;\r\n");
      out.write("let activityCounter = 0;\r\n");
      out.write("\r\n");
      out.write("function updateProgress(percent) {\r\n");
      out.write("progressBar.style.width = percent + \"%\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function completeTask() {\r\n");
      out.write("taskCounter = weightCounter + heightCounter + ageCounter + genderCounter + activityCounter;\r\n");
      out.write("updateProgress((taskCounter / 5) * 100);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.querySelector(\"#weight\").addEventListener(\"input\", function() {\r\n");
      out.write("if (this.value === \"\" || this.value < 30 || this.value > 200) {\r\n");
      out.write("weightCounter = 0;\r\n");
      out.write("} else {\r\n");
      out.write("weightCounter = 1;\r\n");
      out.write("}\r\n");
      out.write("completeTask();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("document.querySelector(\"#height\").addEventListener(\"input\", function() {\r\n");
      out.write("if (this.value === \"\" || this.value < 60 || this.value > 250) {\r\n");
      out.write("heightCounter = 0;\r\n");
      out.write("} else {\r\n");
      out.write("heightCounter = 1;\r\n");
      out.write("}\r\n");
      out.write("completeTask();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("document.querySelector(\"#age\").addEventListener(\"input\", function() {\r\n");
      out.write("if (this.value === \"\" || this.value < 1 || this.value > 120) {\r\n");
      out.write("ageCounter = 0;\r\n");
      out.write("} else {\r\n");
      out.write("ageCounter = 1;\r\n");
      out.write("}\r\n");
      out.write("completeTask();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("document.querySelector(\"#gender\").addEventListener(\"input\", function() {\r\n");
      out.write("if (this.value === \"\") {\r\n");
      out.write("genderCounter = 0;\r\n");
      out.write("} else {\r\n");
      out.write("genderCounter = 1;\r\n");
      out.write("}\r\n");
      out.write("completeTask();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("document.querySelector(\"#activity-level\").addEventListener(\"input\", function() {\r\n");
      out.write("if (this.value === \"\") {\r\n");
      out.write("activityCounter = 0;\r\n");
      out.write("} else {\r\n");
      out.write("activityCounter = 1;\r\n");
      out.write("}\r\n");
      out.write("completeTask();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("document.querySelector(\"[type=reset]\").addEventListener(\"click\", function() {\r\n");
      out.write("taskCounter = 0;\r\n");
      out.write("weightCounter = 0;\r\n");
      out.write("heightCounter = 0;\r\n");
      out.write("ageCounter = 0;\r\n");
      out.write("genderCounter = 0;\r\n");
      out.write("activityCounter = 0;\r\n");
      out.write("document.getElementById(\"result\").innerHTML = \"\";\r\n");
      out.write("document.getElementById(\"calorie-result\").innerHTML = \"\";\r\n");
      out.write("document.querySelector(\".box\").style.minHeight = \"600px\";\r\n");
      out.write("updateProgress(0);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("window.onload = function() {\r\n");
      out.write("document.getElementById(\"bmi-form\").reset();\r\n");
      out.write("progressBar.style.width = \"0%\";\r\n");
      out.write("taskCounter = 0;\r\n");
      out.write("weightCounter = 0;\r\n");
      out.write("heightCounter = 0;\r\n");
      out.write("ageCounter = 0;\r\n");
      out.write("genderCounter = 0;\r\n");
      out.write("activityCounter = 0;\r\n");
      out.write("completeTask();\r\n");
      out.write("};\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
