/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-26 04:06:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
      out.write("	\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>FitFinity</title>\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\" rel=\"stylesheet\">      \r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./image/logo.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css\" integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"footerStyle.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css\" integrity=\"sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\" integrity=\"sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js\" integrity=\"sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js\" integrity=\"sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <style>\r\n");
      out.write("      *{\r\n");
      out.write("        font-family: 'Poppins', sans-serif;\r\n");
      out.write("      }\r\n");
      out.write("       .container .contactInfo{\r\n");
      out.write("        width: 50%;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       .container .contactInfo .box{\r\n");
      out.write("        position: relative;\r\n");
      out.write("        padding: 20px 0;\r\n");
      out.write("        display: flex;\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       .icon{\r\n");
      out.write("        font-size: 40px;\r\n");
      out.write("        margin-right: 20px;\r\n");
      out.write("        color: #0bb288;\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       .contactForm{\r\n");
      out.write("        margin-top: 60px;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       .contactForm .inputBox input,\r\n");
      out.write("       .contactForm .inputBox textarea{\r\n");
      out.write("       \r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 5px 0;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        margin: 10px 0;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-bottom: 2px solid #333;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        resize: none;\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       .contactForm .inputBox span{\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        left: 10px;\r\n");
      out.write("        padding: 5px 0;\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        margin: 10px 0;\r\n");
      out.write("        color: #666;\r\n");
      out.write("        margin-left: 57%;\r\n");
      out.write("        pointer-events: none;\r\n");
      out.write("        transition: 0.2s;\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       .contactForm .inputBox input:focus ~ span,\r\n");
      out.write("       .contactForm .inputBox input:valid ~ span,\r\n");
      out.write("       .contactForm .inputBox textarea:focus ~ span,\r\n");
      out.write("       .contactForm .inputBox textarea:valid ~ span{\r\n");
      out.write("        color: rgb(61, 106, 255);\r\n");
      out.write("        font-size: 17px;\r\n");
      out.write("        transform: translateY(-20px);\r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("       .contactForm .inputBox input[type=\"submit\"]{\r\n");
      out.write("        width: 100px;\r\n");
      out.write("        background: rgb(61, 106, 255);\r\n");
      out.write("        color: aliceblue;\r\n");
      out.write("        border: none;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        padding: 7px;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        border-radius: 10px\r\n");
      out.write("       }\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("       /* Slideshow container */\r\n");
      out.write("    \r\n");
      out.write("	    /*#slideshow {\r\n");
      out.write("	    max-width: 600px; \r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    margin: 20px auto; \r\n");
      out.write("	    border: 0.5px solid #ddd; \r\n");
      out.write("	    border-radius: 3px;\r\n");
      out.write("	    background-color: #e0f7fa; \r\n");
      out.write("	    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	    \r\n");
      out.write("	    \r\n");
      out.write("		}*/\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		#slideshow {\r\n");
      out.write("	    max-width: 400px; /* Adjust width here */\r\n");
      out.write("	    position: relative;\r\n");
      out.write("	    margin: 10px auto; /* Adjust margin here */\r\n");
      out.write("	    border: 0.5px solid #ddd; /* Adjust border size here */\r\n");
      out.write("	    border-radius: 3px; /* Adjust border radius here */\r\n");
      out.write("	    background-color: #f5f5f5; /* Adjust background color here */\r\n");
      out.write("	    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);\r\n");
      out.write("	    padding: 20px;\r\n");
      out.write("	    box-sizing: border-box;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#slideshow::before, #slideshow::after {\r\n");
      out.write("	    content: \"\";\r\n");
      out.write("	    position: absolute;\r\n");
      out.write("	    top: 0;\r\n");
      out.write("	    width: 50%;\r\n");
      out.write("	    height: 20px;\r\n");
      out.write("	    background: #f5f5f5;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("    /* Slides */\r\n");
      out.write("    .slide {\r\n");
      out.write("        display: none;\r\n");
      out.write("        padding: 40px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        background-color: #0bb288;/*#e0f7fa*/\r\n");
      out.write("        border: 0.5px solid #ddd; /* Adjust border size here */\r\n");
      out.write("    	border-radius: 4px;\r\n");
      out.write("    	box-shadow: 0 0 10px rgba(0, 0, 0, 0.1); 	\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* The active slide */\r\n");
      out.write("    .slide.active {\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* The slide content */\r\n");
      out.write("    .slide p {\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        line-height: 1.2;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    form {\r\n");
      out.write("            max-width: 400px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("        }\r\n");
      out.write("        label {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("        }\r\n");
      out.write("        input, textarea, select {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 8px;\r\n");
      out.write("            margin-bottom: 16px;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("        select {\r\n");
      out.write("            height: 40px; /* Adjust the height as needed */\r\n");
      out.write("        }\r\n");
      out.write("        button {\r\n");
      out.write("            background-color: #4CAF50;\r\n");
      out.write("            color: white;\r\n");
      out.write("            padding: 10px 15px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 4px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        button:hover {\r\n");
      out.write("            background-color: #45a049;\r\n");
      out.write("        }\r\n");
      out.write("    \r\n");
      out.write("    	\r\n");
      out.write("    	/*rating*/\r\n");
      out.write("	    	.rating {\r\n");
      out.write("	    float:left;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* :not(:checked) is a filter, so that browsers that don’t support :checked don’t \r\n");
      out.write("	   follow these rules. Every browser that supports :checked also supports :not(), so\r\n");
      out.write("	   it doesn’t make the test unnecessarily selective */\r\n");
      out.write("	.rating:not(:checked) > input {\r\n");
      out.write("	    position:absolute;\r\n");
      out.write("	    top:-9999px;\r\n");
      out.write("	    clip:rect(0,0,0,0);\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.rating:not(:checked) > label {\r\n");
      out.write("	    float:right;\r\n");
      out.write("	    width:1em;\r\n");
      out.write("	    padding:0 .1em;\r\n");
      out.write("	    overflow:hidden;\r\n");
      out.write("	    white-space:nowrap;\r\n");
      out.write("	    cursor:pointer;\r\n");
      out.write("	    font-size:200%;\r\n");
      out.write("	    line-height:1.2;\r\n");
      out.write("	    color:#ddd;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.rating:not(:checked) > label:before {\r\n");
      out.write("	    content: '★ ';\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.rating > input:checked ~ label {\r\n");
      out.write("	    color: #f70;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.rating:not(:checked) > label:hover,\r\n");
      out.write("	.rating:not(:checked) > label:hover ~ label {\r\n");
      out.write("	    color: gold;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.rating > input:checked + label:hover,\r\n");
      out.write("	.rating > input:checked + label:hover ~ label,\r\n");
      out.write("	.rating > input:checked ~ label:hover,\r\n");
      out.write("	.rating > input:checked ~ label:hover ~ label,\r\n");
      out.write("	.rating > label:hover ~ input:checked ~ label {\r\n");
      out.write("	    color: gold;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	/*fb form*/\r\n");
      out.write("	body {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("        .feedback-form {\r\n");
      out.write("            width: 700px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("            background-color:#f5f5f5; /*#f5f5f5;*/\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("        }\r\n");
      out.write("        .feedback-form input[type=\"email\"],\r\n");
      out.write("        .feedback-form select,\r\n");
      out.write("        .feedback-form textarea {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("        }\r\n");
      out.write("        .feedback-form button {\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            background-color: #0bb288;\r\n");
      out.write("            border: none;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 3px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        .feedback-form button:hover {\r\n");
      out.write("            background-color: #50C878;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        h2 {\r\n");
      out.write("        	font-family: 'Poppins', sans-serif;\r\n");
      out.write("			font-size: 26px;\r\n");
      out.write("			line-height: 35px;\r\n");
      out.write("			padding: 20px 0;\r\n");
      out.write("		}	\r\n");
      out.write("       \r\n");
      out.write("    </style>\r\n");
      out.write("  </head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <section class=\"contact mt-5\" style=\"font-family: 'Poppins', sans-serif;\">\r\n");
      out.write("        <div class=\"contact\">\r\n");
      out.write("            <h1 style=\"text-align: center;  font-weight: 600;\">Contact Us</h1>\r\n");
      out.write("            <p style=\"text-align: center; font-size: 20px; font-weight: 500;\">How can we help? For all enquires, pelese email us using the form below.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"container row mt-5\">\r\n");
      out.write("            <div class=\"col-3\"></div>\r\n");
      out.write("            <div class=\"contactInfo col-5 mt-5\">\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"icon\">                        \r\n");
      out.write("                        <i class=\"fa-solid fa-envelope\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h4 style=\"font-size: 23px; font-weight: 600;\">Email</h4>\r\n");
      out.write("                        <p style=\"font-size: 16px; font-weight: 500;\">FitFinity@gmail.com</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"icon\">\r\n");
      out.write("                        <i class=\"fa-solid fa-phone\"></i>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h4 style=\"font-size: 23px; font-weight: 600;\">Phone</h4>\r\n");
      out.write("                        <p style=\"font-size: 16px; font-weight: 500;\">+95 1 966 4709</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"box\">\r\n");
      out.write("                    <div class=\"icon\"><i class=\"fa-solid fa-location-dot\"></i></div>\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        <h1 style=\"font-size: 23px; font-weight: 600;\">Address</h1>\r\n");
      out.write("                        <p style=\"font-size: 16px; font-weight: 500;\">V44P+84R, Parami Road, Yangon, Myanmar (Burma)</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("     \r\n");
      out.write("        <div class=\"contactForm col-4\">\r\n");
      out.write("      <form class=\"feedback-form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/FeedbackServlet\" method=\"post\">\r\n");
      out.write("      		<span>LEAVE A MESSAGE</span>\r\n");
      out.write("      		<h2>We love to hear from you</h2>\r\n");
      out.write("	        <label for=\"email\">Email:</label>\r\n");
      out.write("	        <input type=\"email\" id=\"email\" name=\"email\" required>\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"rating\">Rating:</label>\r\n");
      out.write("	    <div class=\"rating\">\r\n");
      out.write("	        <input type=\"radio\" id=\"star5\" name=\"rating\" value=\"5\" /><label for=\"star5\" title=\"Excellent\">5 stars</label>\r\n");
      out.write("	        <input type=\"radio\" id=\"star4\" name=\"rating\" value=\"4\" /><label for=\"star4\" title=\"Good\">4 stars</label>\r\n");
      out.write("	        <input type=\"radio\" id=\"star3\" name=\"rating\" value=\"3\" /><label for=\"star3\" title=\"Average\">3 stars</label>\r\n");
      out.write("	        <input type=\"radio\" id=\"star2\" name=\"rating\" value=\"2\" /><label for=\"star2\" title=\"Fair\">2 stars</label>\r\n");
      out.write("	        <input type=\"radio\" id=\"star1\" name=\"rating\" value=\"1\" /><label for=\"star1\" title=\"Poor\">1 star</label>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <br>\r\n");
      out.write("	    <br>\r\n");
      out.write("	\r\n");
      out.write("	        <label for=\"feedback\">Your Feedback:</label>\r\n");
      out.write("		    <textarea id=\"feedback\" name=\"feedback\" rows=\"4\" required></textarea>\r\n");
      out.write("		\r\n");
      out.write("		    <button type=\"submit\">Submit Feedback</button>\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    ");
 String message = (String) request.getAttribute("message");
    
    if (message!=null)
    { 
      out.write("\r\n");
      out.write("    	<h2>");
      out.print(message);
      out.write("</h2>\r\n");
      out.write("    ");
 } 
    
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    ");

    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fitfinity", "root", "");
    Statement stmt = con.createStatement();
    ResultSet rs = stmt.executeQuery("SELECT patientEmail, feedbackText, rating FROM feedback WHERE rating > 2");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"slideshow\">\r\n");
      out.write("    ");
 while(rs.next()) { 
      out.write("\r\n");
      out.write("        <div class=\"slide\">\r\n");
      out.write("        	");
      out.print( rs.getString("feedbackText") );
      out.write("<br>\r\n");
      out.write("        	");
      out.print( rs.getString("patientEmail") );
      out.write("<br>\r\n");
      out.write("            ");
 int rating = Integer.parseInt(rs.getString("rating")); 
      out.write("\r\n");
      out.write("            ");
 for(int i = 0; i < rating; i++) { 
      out.write("\r\n");
      out.write("                ★\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("            ");
 for(int i = rating; i < 5; i++) { 
      out.write("\r\n");
      out.write("                ☆\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<script>\r\n");
      out.write("    let slideIndex = 0;\r\n");
      out.write("    showSlides();\r\n");
      out.write("\r\n");
      out.write("    function showSlides() {\r\n");
      out.write("        let i;\r\n");
      out.write("        let slides = document.getElementsByClassName(\"slide\");\r\n");
      out.write("        for (i = 0; i < slides.length; i++) {\r\n");
      out.write("            slides[i].style.display = \"none\";  \r\n");
      out.write("        }\r\n");
      out.write("        slideIndex++;\r\n");
      out.write("        if (slideIndex > slides.length) {slideIndex = 1}    \r\n");
      out.write("        slides[slideIndex-1].style.display = \"block\";  \r\n");
      out.write("        setTimeout(showSlides, 2000); // Change slide every 2 seconds\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <section class=\" row mt-5 mb-5\" >\r\n");
      out.write("        <div class=\"col-2\"></div>\r\n");
      out.write("        <div class=\"col-8\">\r\n");
      out.write("          <iframe src=\"https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3818.404402058949!2d96.13308881455715!3d16.8558781223534!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30c1936f625d4ba7%3A0x9676670831769962!2sUniversity%20of%20Information%20Technology(UIT)!5e0!3m2!1sen!2smm!4v1675524353877!5m2!1sen!2smm\"  width=\"100%\" height=\"400\" style=\"border:0; border-radius: 20px; box-shadow: 1px 1px 10px black;\" allowfullscreen=\"\" loading=\"lazy\" referrerpolicy=\"no-referrer-when-downgrade\"></iframe>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-2\"></div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("      <div style=\" max-width: 100%;\" class=\"bg-dark ps-5 pt-1 pb-0 pe-5\">\r\n");
      out.write("          <footer class=\"py-2\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-6 col-md-2 mb-3\">\r\n");
      out.write("                <h1 class=\" text-warning\">FitFinity</h1>\r\n");
      out.write("                <ul class=\"nav flex-column mt-4\">\r\n");
      out.write("                  <li class=\"nav-item mb-2\"><a href=\"./main.html\" class=\" p-0\">Home</a></li>\r\n");
      out.write("                  <li class=\"nav-item mb-2\"><a href=\"./helpcenter.html\" class=\" p-0\">Help Center</a></li>\r\n");
      out.write("                  <li class=\"nav-item mb-2\"><a href=\"./contact.html\" class=\" p-0\">Contact Us</a></li>\r\n");
      out.write("                  <li class=\"nav-item mb-2\"><a href=\"./bmi-calculator.html\" target=\"_blank\" class=\"nav-item p-0\">BMI Calculator</a></li>\r\n");
      out.write("                  <li class=\"nav-item mb-2\"><a href=\"./signUp.html\" class=\" p-0\">Sign Up</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("         \r\n");
      out.write("              <div class=\"col-6 col-md-2 mb-3 mt-3\">\r\n");
      out.write("                <ul class=\"nav flex-column\" style=\"margin-top: 93px;\">\r\n");
      out.write("                  <li class=\"nav-item mb-2\"><a href=\"./advice.html\" class=\" p-0\">Advice</a></li>\r\n");
      out.write("                  <li class=\"nav-item mb-2\"><a href=\"./Course-Page.html\" class=\" p-0\">Courses</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("              <div class=\"col-md-5 offset-md-1 mb-3\" style=\"margin-top: 80px;\">\r\n");
      out.write("                <form>\r\n");
      out.write("                  <h5 class=\" text-info\">Subscribe to our newsletter</h5>\r\n");
      out.write("                  <p class=\" text-light\">Monthly digest of what's new and exciting from us.</p>\r\n");
      out.write("                  <div class=\"d-flex flex-column flex-sm-row w-100 gap-2\">\r\n");
      out.write("                    <label for=\"newsletter1\" class=\"visually-hidden\">Email address</label>\r\n");
      out.write("                    <input id=\"newsletter1\" type=\"text\" class=\"form-control\" placeholder=\"Email address\">\r\n");
      out.write("                    <button class=\"btn btn-primary\" type=\"button\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">Subscribe</button>\r\n");
      out.write("                    <div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("                      <div class=\"modal-dialog\">\r\n");
      out.write("                        <div class=\"modal-content\">\r\n");
      out.write("                          <div class=\"modal-body\">\r\n");
      out.write("                            Subscribed successfully! <br> New updates about our website and activities will be informed with the Email fast.\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"modal-footer\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </form>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top\">\r\n");
      out.write("              <p style=\"color: greenyellow;\">&copy; 2022 Company, Inc. All rights reserved.</p>\r\n");
      out.write("              <!-- Button trigger modal -->\r\n");
      out.write("              <p style=\"color: yellow; cursor: pointer;\" data-bs-toggle=\"modal\" data-bs-target=\"#staticBackdrop\">\r\n");
      out.write("                Privacy Policy\r\n");
      out.write("              </p>\r\n");
      out.write("              <!-- Modal -->\r\n");
      out.write("              <div class=\"modal fade\" id=\"staticBackdrop\" data-bs-backdrop=\"static\" data-bs-keyboard=\"false\" tabindex=\"-1\" aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\r\n");
      out.write("                <div class=\"modal-dialog modal-dialog-scrollable\">\r\n");
      out.write("                  <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                      <h1 class=\"modal-title\" id=\"staticBackdropLabel\">Privacy Policy</h1>\r\n");
      out.write("                      <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                      <strong>Introduction</strong> <br> Fitfinity is a workout and fitness website that is committed to protecting the privacy of our users. This Privacy Policy explains the types of information we collect, how we use it, and the steps we take to protect it. By using our website and services, you agree to the collection, use, and disclosure of your information as described in this Privacy Policy.\r\n");
      out.write("                      <br><br>\r\n");
      out.write("                      <strong>Privacy Policy</strong><br> This Privacy Policy describes FitFinity Inc.'s (“FitFinity”) policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.\r\n");
      out.write("                      <br><br>\r\n");
      out.write("                      <strong>Information We Collect</strong><br>We collect two types of information from our users: personally identifiable information and non-personally identifiable information.\r\n");
      out.write("                      We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.\r\n");
      out.write("                      <br><br>\r\n");
      out.write("                      If you have any questions about this Privacy Policy, You can contact us by email: privacy@fitfinity.com. <br><br>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"modal-footer\">\r\n");
      out.write("                      <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("                      <button type=\"button\" class=\"btn btn-primary\" data-bs-dismiss=\"modal\">Understood</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <ul class=\"list-unstyled d-flex\" style=\"margin-right: 30px;\">\r\n");
      out.write("                <li class=\"ms-3\"><a class=\"link-dark\" href=\"https://www.facebook.com/\" target=\"_blank\"><img style=\"width: 40px;\" width=\"40px\" src=\"./image/facebook.png\" alt=\"\"></a></li>\r\n");
      out.write("                <li class=\"ms-3\"><a class=\"link-dark\" href=\"https://www.instagram.com/\" target=\"_blank\"><img style=\"width: 40px;\" width=\"40px\" src=\"./image/instagram.png\" alt=\"\"></a></li>\r\n");
      out.write("                <li class=\"ms-3\"><a class=\"link-dark\" href=\"https://twitter.com/\" target=\"_blank\"><img style=\"width: 40px;\" width=\"40px\" src=\"./image/twitter.png\" alt=\"\"></a></li>\r\n");
      out.write("                <li class=\"ms-3\"><a class=\"link-dark\" href=\"https://www.youtube.com/\" target=\"_blank\"><img style=\"width: 40px;\" width=\"40px\" src=\"./image/youtube.png\" alt=\"\"></a></li>\r\n");
      out.write("                <li class=\"ms-3\"><a class=\"link-dark\" href=\"https://www.pinterest.com/\" target=\"_blank\"><img style=\"width: 40px;\" width=\"40px\" src=\"./image/pinterest.png\" alt=\"\"></a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
