/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-03 11:39:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class DrSchedule_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <title>Assign Doctor Schedule</title>\r\n");
      out.write("  <!-- Bootstrap CSS -->\r\n");
      out.write("  <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <!-- Custom CSS -->\r\n");
      out.write("  <style>\r\n");
      out.write("    /* Add custom styles here */\r\n");
      out.write("    .shift-btn {\r\n");
      out.write("      margin-right: 10px;\r\n");
      out.write("      margin-bottom: 5px;\r\n");
      out.write("      display: none; /* Hide actual checkboxes */\r\n");
      out.write("    }\r\n");
      out.write("    .shift-btn.active-label {\r\n");
      out.write("      background-color: #007bff;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    .shift-btn.active-label::before {\r\n");
      out.write("      content: \"✔\"; /* Display checkmark */\r\n");
      out.write("      margin-right: 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .shift-btn:checked + label {\r\n");
      out.write("      background-color: #007bff;\r\n");
      out.write("      color: #fff;\r\n");
      out.write("    }\r\n");
      out.write("    th {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    td {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .error-message {\r\n");
      out.write("      color: red;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <h2 class=\"mt-5\">Assign Doctor Schedule</h2>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
 String error = request.getParameter("error");
       if (error != null && !error.isEmpty()) { 
      out.write("\r\n");
      out.write("      <div class=\"error-message\">\r\n");
      out.write("        ");
      out.print( error );
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    ");
 } 
      out.write("\r\n");
      out.write("    <form action=\"AddDoctorSchedule\" method=\"post\">\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label for=\"doctorID\">Doctor ID</label>\r\n");
      out.write("        <input type=\"text\" class=\"form-control\" id=\"doctorID\" name=\"doctorID\" placeholder=\"Enter Doctor's ID\">\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"form-group\">\r\n");
      out.write("        <label>Schedule</label>\r\n");
      out.write("        <table class=\"table\">\r\n");
      out.write("          <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <th>Day</th>\r\n");
      out.write("              <th>Shift 1</th>\r\n");
      out.write("              <th>Shift 2</th>\r\n");
      out.write("              <th>Shift 3</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </thead>\r\n");
      out.write("          <tbody>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Monday</td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"mondayShift1\" class=\"shift-btn\" name=\"shift\" value=\"Monday,10:00AM - 12:00PM\">\r\n");
      out.write("                <label for=\"mondayShift1\" class=\"btn btn-outline-success shift-btn-label\">10:00AM - 12:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"mondayShift2\" class=\"shift-btn\" name=\"shift\" value=\"Monday,2:00PM - 4:00PM\">\r\n");
      out.write("                <label for=\"mondayShift2\" class=\"btn btn-outline-success shift-btn-label\">2:00PM - 4:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"mondayShift3\" class=\"shift-btn\" name=\"shift\" value=\"Monday,6:00PM - 8:00PM\">\r\n");
      out.write("                <label for=\"mondayShift3\" class=\"btn btn-outline-success shift-btn-label\">6:00PM - 8:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <!-- Tuesday -->\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Tuesday</td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"tuesdayShift1\" class=\"shift-btn\" name=\"shift\" value=\"Tuesday,10:00AM - 12:00PM\">\r\n");
      out.write("                <label for=\"tuesdayShift1\" class=\"btn btn-outline-success shift-btn-label\">10:00AM - 12:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"tuesdayShift2\" class=\"shift-btn\" name=\"shift\" value=\"Tuesday,2:00PM - 4:00PM\">\r\n");
      out.write("                <label for=\"tuesdayShift2\" class=\"btn btn-outline-success shift-btn-label\">2:00PM - 4:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"tuesdayShift3\" class=\"shift-btn\" name=\"shift\" value=\"Tuesday,6:00PM - 8:00PM\">\r\n");
      out.write("                <label for=\"tuesdayShift3\" class=\"btn btn-outline-success shift-btn-label\">6:00PM - 8:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <!-- Wednesday -->\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Wednesday</td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"wednesdayShift1\" class=\"shift-btn\" name=\"shift\" value=\"Wednesday,10:00AM - 12:00PM\">\r\n");
      out.write("                <label for=\"wednesdayShift1\" class=\"btn btn-outline-success shift-btn-label\">10:00AM - 12:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"wednesdayShift2\" class=\"shift-btn\" name=\"shift\" value=\"Wednesday,2:00PM - 4:00PM\">\r\n");
      out.write("                <label for=\"wednesdayShift2\" class=\"btn btn-outline-success shift-btn-label\">2:00PM - 4:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"wednesdayShift3\" class=\"shift-btn\" name=\"shift\" value=\"Wednesday,6:00PM - 8:00PM\">\r\n");
      out.write("                <label for=\"wednesdayShift3\" class=\"btn btn-outline-success shift-btn-label\">6:00PM - 8:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <!-- Thursday -->\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Thursday</td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"thursdayShift1\" class=\"shift-btn\" name=\"shift\" value=\"Thursday,10:00AM - 12:00PM\">\r\n");
      out.write("                <label for=\"thursdayShift1\" class=\"btn btn-outline-success shift-btn-label\">10:00AM - 12:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"thursdayShift2\" class=\"shift-btn\" name=\"shift\" value=\"Thursday,2:00PM - 4:00PM\">\r\n");
      out.write("                <label for=\"thursdayShift2\" class=\"btn btn-outline-success shift-btn-label\">2:00PM - 4:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"thursdayShift3\" class=\"shift-btn\" name=\"shift\" value=\"Thursday,6:00PM - 8:00PM\">\r\n");
      out.write("                <label for=\"thursdayShift3\" class=\"btn btn-outline-success shift-btn-label\">6:00PM - 8:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <!-- Friday -->\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Friday</td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"fridayShift1\" class=\"shift-btn\" name=\"shift\" value=\"Friday,10:00AM - 12:00PM\">\r\n");
      out.write("                <label for=\"fridayShift1\" class=\"btn btn-outline-success shift-btn-label\">10:00AM - 12:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"fridayShift2\" class=\"shift-btn\" name=\"shift\" value=\"Friday,2:00PM - 4:00PM\">\r\n");
      out.write("                <label for=\"fridayShift2\" class=\"btn btn-outline-success shift-btn-label\">2:00PM - 4:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"fridayShift3\" class=\"shift-btn\" name=\"shift\" value=\"Friday,6:00PM - 8:00PM\">\r\n");
      out.write("                <label for=\"fridayShift3\" class=\"btn btn-outline-success shift-btn-label\">6:00PM - 8:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <!-- Saturday -->\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Saturday</td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"saturdayShift1\" class=\"shift-btn\" name=\"shift\" value=\"Saturday,10:00AM - 12:00PM\">\r\n");
      out.write("                <label for=\"saturdayShift1\" class=\"btn btn-outline-success shift-btn-label\">10:00AM - 12:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"saturdayShift2\" class=\"shift-btn\" name=\"shift\" value=\"Saturday,2:00PM - 4:00PM\">\r\n");
      out.write("                <label for=\"saturdayShift2\" class=\"btn btn-outline-success shift-btn-label\">2:00PM - 4:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"saturdayShift3\" class=\"shift-btn\" name=\"shift\" value=\"Saturday,6:00PM - 8:00PM\">\r\n");
      out.write("                <label for=\"saturdayShift3\" class=\"btn btn-outline-success shift-btn-label\">6:00PM - 8:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <!-- Sunday -->\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td>Sunday</td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"sundayShift1\" class=\"shift-btn\" name=\"shift\" value=\"Sunday,10:00AM - 12:00PM\">\r\n");
      out.write("                <label for=\"sundayShift1\" class=\"btn btn-outline-success shift-btn-label\">10:00AM - 12:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"sundayShift2\" class=\"shift-btn\" name=\"shift\" value=\"Sunday,2:00PM - 4:00PM\">\r\n");
      out.write("                <label for=\"sundayShift2\" class=\"btn btn-outline-success shift-btn-label\">2:00PM - 4:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input type=\"checkbox\" id=\"sundayShift3\" class=\"shift-btn\" name=\"shift\" value=\"Sunday,6:00PM - 8:00PM\">\r\n");
      out.write("                <label for=\"sundayShift3\" class=\"btn btn-outline-success shift-btn-label\">6:00PM - 8:00PM</label>\r\n");
      out.write("              </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("      </div>\r\n");
      out.write("      <button style=\"margin-left: 15%; width: 70%; \" type=\"submit\" class=\"btn btn-success\">Submit</button>\r\n");
      out.write("    </form>\r\n");
      out.write("    <a href=\"./adminDashboard.jsp\"><button style=\"margin-top: 20px; margin-left: 15%; width: 70%; \" type=\"submit\" class=\"btn btn-success\">Back</button></a>\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>\r\n");
      out.write("    <br>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Bootstrap JS -->\r\n");
      out.write("  <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <!-- Custom JS -->\r\n");
      out.write("  <script>\r\n");
      out.write("    // Disable selecting other shifts in the same day once one shift is selected\r\n");
      out.write("    $('.shift-btn').click(function() {\r\n");
      out.write("      var day = $(this).parent().prevAll('td').last().text().trim();\r\n");
      out.write("      $('.shift-btn').each(function() {\r\n");
      out.write("        if ($(this).parent().prevAll('td').last().text().trim() === day && $(this).hasClass('active')) {\r\n");
      out.write("          $(this).prop('checked', false);\r\n");
      out.write("          $(this).removeClass('active');\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("      $(this).addClass('active');\r\n");
      out.write("    });\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
