/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-27 18:13:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class drSignUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Form Validation</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("    <link rel=\"icon\" href=\"./image/logo.png\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Fonts -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap\" rel=\"stylesheet\" />\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("            font-family: \"Poppins\", sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            background: rgb(53,117,254);\r\n");
      out.write("            background: linear-gradient(180deg, #0bb288 0%, #0bb288 0%, white 100%);\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("            background-position: center;\r\n");
      out.write("            background-attachment: fixed;\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-size: cover;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container {\r\n");
      out.write("            width: 90vw;\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            padding: 2em 1.5em;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            margin: 70px auto;\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        h4 {\r\n");
      out.write("            font-size: 1.5em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .input-section {\r\n");
      out.write("            margin: 0.5em 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label, .error-message {\r\n");
      out.write("            display: block;\r\n");
      out.write("            font-size: 1em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        label {\r\n");
      out.write("            margin-bottom: 0.5em;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .error-message {\r\n");
      out.write("            margin-top: 0.2em;\r\n");
      out.write("            color: red;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input, select, button {\r\n");
      out.write("            display: block;\r\n");
      out.write("            outline: none;\r\n");
      out.write("            border: 1px solid #75777d;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            border-radius: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input[type=\"radio\"] {\r\n");
      out.write("            width: fit-content;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        button {\r\n");
      out.write("            font-size: 1em;\r\n");
      out.write("            background-color: #0bb288;\r\n");
      out.write("            border: 1px solid #75777d;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            padding: 0.8em 0;\r\n");
      out.write("            margin-top: 2em;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .required-color {\r\n");
      out.write("            color: #ff4747;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .error {\r\n");
      out.write("            border-color: #ff4747;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .valid {\r\n");
      out.write("            border-color: #37a137;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hide {\r\n");
      out.write("            display: none;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media only screen and (max-width: 450px) {\r\n");
      out.write("            .container {\r\n");
      out.write("                font-size: 14px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
String DrIDSet = ""; 
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AddDoctor\" method=\"post\">\r\n");
      out.write("        <h4>Create Doctor's Account</h4>\r\n");
      out.write("\r\n");
      out.write("        <!-- Doctor ID -->\r\n");
      out.write("        <div class=\"input-section\">\r\n");
      out.write("            <label>\r\n");
      out.write("                <i class=\"fa-solid fa-id-card-clip\" style=\"color: #0bb288;\"></i> Doctor ID <span class=\"required-color\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            ");
  if(request.getAttribute("doctorID")==null){DrIDSet = "Dr-";} 
      out.write("\r\n");
      out.write("            <input type=\"text\" placeholder=\"Enter doctor's id\" name=\"doctorID\" id=\"doctorID\" value=\"");
      out.print( DrIDSet );
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.doctorID}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("            ");
 String error1 = (String) request.getAttribute("message1");
            if(error1!=null)
            {
            
      out.write("\r\n");
      out.write("            <span class=\"error-message\"> ");
      out.print( error1 );
      out.write("  </span> <br>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Doctor Name -->\r\n");
      out.write("        <div class=\"input-section\">\r\n");
      out.write("            <label>\r\n");
      out.write("                <i class=\"fa-solid fa-user\" style=\"color: #0bb288;\"></i> Doctor Name <span class=\"required-color\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <input type=\"text\" placeholder=\"Enter doctor's name\" name=\"doctorName\" id=\"doctorName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.doctorName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("            ");
 String error2 = (String) request.getAttribute("message2");
            if(error2!=null)
            {
            
      out.write("\r\n");
      out.write("            <span class=\"error-message\"> ");
      out.print( error2 );
      out.write("  </span> <br>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Doctor Email -->\r\n");
      out.write("        <div class=\"input-section\">\r\n");
      out.write("            <label>\r\n");
      out.write("                <i class=\"fa-regular fa-envelope\" style=\"color: #0bb288;\"></i> Doctor Email <span class=\"required-color\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <input type=\"text\" name=\"doctorEmail\" id=\"doctorEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.doctorEmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Enter doctor's email\" required>\r\n");
      out.write("            ");
 String error3 = (String) request.getAttribute("message3");
            if(error3!=null)
            {
            
      out.write("\r\n");
      out.write("            <span class=\"error-message\"> ");
      out.print( error3 );
      out.write("  </span> <br>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Doctor Tel -->\r\n");
      out.write("        <div class=\"input-section\">\r\n");
      out.write("            <label>\r\n");
      out.write("                <i class=\"fa-solid fa-phone\" style=\"color: #0bb288;\"></i> Doctor Tel <span class=\"required-color\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <input type=\"text\" name=\"doctorTel\" id=\"doctorTel\" placeholder=\"Enter doctor's phone: 09\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.doctorTel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required>\r\n");
      out.write("            ");
 String error4 = (String) request.getAttribute("message4");
            if(error4!=null)
            {
            
      out.write("\r\n");
      out.write("            <span class=\"error-message\"> ");
      out.print( error4 );
      out.write("  </span> <br>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Doctor Password -->\r\n");
      out.write("        <div class=\"input-section\">\r\n");
      out.write("            <label>\r\n");
      out.write("                <i class=\"fa-solid fa-lock\" style=\"color: #0bb288;\"></i> Doctor Password <span class=\"required-color\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <input type=\"password\" placeholder=\"Enter doctor's password\" name=\"doctorPwd\" id=\"doctorPwd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.doctorPwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("            ");
 String error5 = (String) request.getAttribute("message5");
            if(error5!=null)
            {
            
      out.write("\r\n");
      out.write("            <span class=\"error-message\"> ");
      out.print( error5 );
      out.write("  </span> <br>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Department -->\r\n");
      out.write("        <div class=\"input-section\">\r\n");
      out.write("            <label>\r\n");
      out.write("                <i class=\"fa-regular fa-hospital\" style=\"color: #0bb288;\"></i> Department<span class=\"required-color\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <select name=\"deptID\" id=\"deptID\" required>\r\n");
      out.write("                <option value=\"\">Select Department</option>\r\n");
      out.write("                <option value=\"D-1\">Cardiology</option>\r\n");
      out.write("                <option value=\"D-2\">Dermatology</option>\r\n");
      out.write("                <option value=\"D-3\">Otolaryngology</option>\r\n");
      out.write("                <option value=\"D-4\">Emergency</option>\r\n");
      out.write("                <option value=\"D-5\">Orthopaedic</option>\r\n");
      out.write("                <option value=\"D-6\">Neurology</option>\r\n");
      out.write("                <option value=\"D-7\">Obstetrics & Gynaecology</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            ");
 String error6 = (String) request.getAttribute("message6");
            if(error6!=null)
            {
            
      out.write("\r\n");
      out.write("            <span class=\"error-message\"> ");
      out.print( error6 );
      out.write("  </span> <br>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Role -->\r\n");
      out.write("        <div class=\"input-section\">\r\n");
      out.write("            <label>\r\n");
      out.write("                <i class=\"fa-solid fa-user-doctor\" style=\"color: #0bb288;\"></i> Role<span class=\"required-color\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <select name=\"roleID\" id=\"roleID\" required>\r\n");
      out.write("                <option value=\"\">Select Role</option>\r\n");
      out.write("                <option value=\"R-1\">Professor</option>\r\n");
      out.write("                <option value=\"R-2\">Assistant Professor</option>\r\n");
      out.write("                <option value=\"R-3\">Fellow</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            ");
 String error8 = (String) request.getAttribute("message8");
            if(error8!=null)
            {
            
      out.write("\r\n");
      out.write("            <span class=\"error-message\"> ");
      out.print( error8 );
      out.write("  </span> <br>\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <br>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Submit Button -->\r\n");
      out.write("        <button id=\"submit-button\" class=\"btn btn-success\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\" style=\"background-color: #0bb288\"> Signup </button>\r\n");
      out.write("        <button style=\"background-color: #0bb288\">\r\n");
      out.write("            <a style=\"padding-left: 45%; padding-right: 45%; padding-top: 2%; padding-bottom: 2%; text-decoration: none; color: #ffffff;\" href=\"./adminDashboard.jsp\"> Back </a>\r\n");
      out.write("        </button>\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
