/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-02-27 16:07:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class guestDoctors_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"no-js\" lang=\"\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"utf-8\" />\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\" />\r\n");
      out.write("    <title>Fitfinity</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"icon\" href=\"./assets/image/logo/logo.svg\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\" integrity=\"sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <!-- Place favicon.ico in the root directory -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Nunito:wght@500&display=swap\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Pacifico&display=swap\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("    />\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- ========================= CSS here ========================= -->\r\n");
      out.write("    <link\r\n");
      out.write("      href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("      rel=\"stylesheet\"\r\n");
      out.write("      integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    />\r\n");
      out.write("    \r\n");
      out.write("	<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("      body {\r\n");
      out.write("        background-color: #f0f0f0;\r\n");
      out.write("        font-family: \"Poppins\", sans-serif;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .doctor-card {\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("        padding: 20px;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        display: flex; /* Use flexbox for layout */\r\n");
      out.write("        align-items: center; /* Center align content vertically */\r\n");
      out.write("        border-bottom: 1px solid #A6A6A6;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .doctor-card h5 {\r\n");
      out.write("        margin-bottom: 15px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .doctor-card h3 {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        color: #00594d;\r\n");
      out.write("        font-family: \"Poppins\", sans-serif;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .doctor-card p {\r\n");
      out.write("      	color: #646569;\r\n");
      out.write("        font-size: 17px;\r\n");
      out.write("        margin-bottom: 5px;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .doctor-card .user-img {\r\n");
      out.write("        width: 170px; /* Set width of the image */\r\n");
      out.write("        height: auto; /* Maintain aspect ratio */\r\n");
      out.write("        margin-top: 20px%;\r\n");
      out.write("        border-radius: 10%; /* Rounded corners */\r\n");
      out.write("        margin-left: 20px; /* Margin for spacing */\r\n");
      out.write("        margin-right: 50px; /* Margin for spacing */\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .doctor-card-content {\r\n");
      out.write("        flex: 1; /* Take up remaining space */\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .doctor-card a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        color: #e8bd70;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .doctor-card-tag {\r\n");
      out.write("      background-color: #e8bd70;\r\n");
      out.write("      color: #ffffff;\r\n");
      out.write("      border-radius: 5px;\r\n");
      out.write("      padding: 5px 10px;\r\n");
      out.write("      margin-bottom: 10px;\r\n");
      out.write("      margin-right: 10px;\r\n");
      out.write("      font-size: 14px;\r\n");
      out.write("      text-transform: uppercase;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    btn:hover {\r\n");
      out.write("	background-color: #E8BD70;\r\n");
      out.write("	color: white;\r\n");
      out.write("}\r\n");
      out.write("	</style>\r\n");
      out.write("	\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/bootstrap-5.0.5-alpha.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/LineIcons.2.0.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/animate.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/tiny-slider.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/css/main.css\" />\r\n");
      out.write("  </head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <header id=\"home\" class=\"header\">\r\n");
      out.write("      <div class=\"header-wrapper\">\r\n");
      out.write("        <div class=\"header-top theme-bg\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-md-8\">\r\n");
      out.write("                <div class=\"header-top-left text-center text-md-left\">\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\"\r\n");
      out.write("                        ><i class=\"lni lni-phone\"></i> +959985056890</a\r\n");
      out.write("                      >\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\"\r\n");
      out.write("                        ><i class=\"lni lni-envelope\"></i> fitfinity@gmail.com</a\r\n");
      out.write("                      >\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"col-md-4\">\r\n");
      out.write("                <div class=\"header-top-right d-none d-md-block\">\r\n");
      out.write("                  <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\"><i class=\"lni lni-facebook-filled\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\"><i class=\"lni lni-twitter-filled\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <a href=\"#\"><i class=\"lni lni-linkedin-original\"></i></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-area\">\r\n");
      out.write("          <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("              <div class=\"col-lg-12\">\r\n");
      out.write("                <nav class=\"navbar navbar-expand-lg\">\r\n");
      out.write("                  <a class=\"navbar-brand\" href=\"index.html\">\r\n");
      out.write("                    <img\r\n");
      out.write("                      style=\"width: 70px\"\r\n");
      out.write("                      src=\"assets/image/logo/MainLogosvg.svg\"\r\n");
      out.write("                      alt=\"Logo\"\r\n");
      out.write("                    />\r\n");
      out.write("                    <h4 style=\"display: inline\">\r\n");
      out.write("                      <span\r\n");
      out.write("                        style=\"\r\n");
      out.write("                          color: #0bb288;\r\n");
      out.write("                          margin-left: 0px;\r\n");
      out.write("                          font-family: 'Nunito', sans-serif;\r\n");
      out.write("                          font-weight: 700;\r\n");
      out.write("                        \"\r\n");
      out.write("                        >FitFinity</span\r\n");
      out.write("                      >\r\n");
      out.write("                      <span\r\n");
      out.write("                        style=\"\r\n");
      out.write("                          color: #af976d;\r\n");
      out.write("                          margin-left: 0px;\r\n");
      out.write("                          font-family: 'Nunito', sans-serif;\r\n");
      out.write("                          font-weight: 700;\r\n");
      out.write("                        \"\r\n");
      out.write("                        >Healthcare</span\r\n");
      out.write("                      >\r\n");
      out.write("                    </h4>\r\n");
      out.write("                    <h6\r\n");
      out.write("                      style=\"margin-left: 26%; margin-top: -5%\"\r\n");
      out.write("                      class=\"navDiv\"\r\n");
      out.write("                    >\r\n");
      out.write("                      <span\r\n");
      out.write("                        style=\"color: #af976d; font-family: 'Pacifico', cursive\"\r\n");
      out.write("                        >Health For</span\r\n");
      out.write("                      >\r\n");
      out.write("                      <span\r\n");
      out.write("                        style=\"color: #0bb288; font-family: 'Pacifico', cursive\"\r\n");
      out.write("                        >Everyone</span\r\n");
      out.write("                      >\r\n");
      out.write("                    </h6>\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <button\r\n");
      out.write("                    class=\"navbar-toggler\"\r\n");
      out.write("                    type=\"button\"\r\n");
      out.write("                    data-toggle=\"collapse\"\r\n");
      out.write("                    data-target=\"#navbarSupportedContent\"\r\n");
      out.write("                    aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("                    aria-expanded=\"false\"\r\n");
      out.write("                    aria-label=\"Toggle navigation\"\r\n");
      out.write("                  >\r\n");
      out.write("                    <span class=\"toggler-icon\"></span>\r\n");
      out.write("                    <span class=\"toggler-icon\"></span>\r\n");
      out.write("                    <span class=\"toggler-icon\"></span>\r\n");
      out.write("                  </button>\r\n");
      out.write("\r\n");
      out.write("                  <div\r\n");
      out.write("                    class=\"collapse navbar-collapse sub-menu-bar\"\r\n");
      out.write("                    id=\"navbarSupportedContent\"\r\n");
      out.write("                  >\r\n");
      out.write("                    <ul id=\"nav\" class=\"navbar-nav ml-auto\">\r\n");
      out.write("\r\n");
      out.write("                      <li class=\"nav-item mt-3\">\r\n");
      out.write("                        <a class=\"active\" href=\"#\">Find Doctor</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"nav-item mt-3\">\r\n");
      out.write("                        <a class=\"\" href=\"./BMI.jsp\">BMI</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li class=\"nav-item mt-3\">\r\n");
      out.write("                        <a class=\"\" href=\"./feedback.jsp\">Contact</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("\r\n");
      out.write("                      <li class=\"nav-item mt-1\">\r\n");
      out.write("			            <div class=\"dropdown-center me-5\">\r\n");
      out.write("			              <button class=\"btn p-1 pe-2 ps-2 rounded-3\" type=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("			                <i style=\"color: #E8BD70; font-size: 30px;\" class=\"fa-solid fa-user\"></i>\r\n");
      out.write("			              </button>\r\n");
      out.write("			              <ul class=\"dropdown-menu\">\r\n");
      out.write("			                <li><a style=\"font-size: 17px;\" class=\"dropdown-item\" href=\"#\"> Guest <img style=\"margin-left: 30px;\" class=\" rounded-circle\" width=\"50px\" src=\"/image/profile1.jpg\" alt=\"\"></a></li>\r\n");
      out.write("			                <li><hr class=\"dropdown-divider\"></li>\r\n");
      out.write("			                <li><a style=\"font-size: 17px;\" class=\"dropdown-item\" href=\"./main.jsp\">LogOut</a></li>\r\n");
      out.write("			              </ul>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- navbar collapse -->\r\n");
      out.write("                </nav>\r\n");
      out.write("                <!-- navbar -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- row -->\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- container -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- navbar area -->\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"container mt-5\">\r\n");
      out.write("    <h3 style=\"color: #00594d;\" >Doctors List</h3>\r\n");
      out.write("    <div class=\"dropdown\">\r\n");
      out.write("      <button style=\"background-color: #0bb288; color: white;\" class=\"btn dropdown-toggle\" type=\"button\" id=\"dropdownMenuButton\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("        Select a department\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"dropdown-menu drdrop\" aria-labelledby=\"dropdownMenuButton\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("      <div id=\"doctorList\" class=\"row\">\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("			    <div class=\"doctor-card\">\r\n");
      out.write("			        <div class=\"doctor-card-content\">\r\n");
      out.write("			            <span class=\"doctor-card-tag\">&#8226; Real-time Booking</span>\r\n");
      out.write("			            <span class=\"doctor-card-tag\">&#8226; Fitfinity</span>\r\n");
      out.write("			            <h3> Dr. U Win Myint </h3>\r\n");
      out.write("			            <p>Email: winmyint@gmail.com</p>\r\n");
      out.write("			            <p>Tel: 09250700588</p>\r\n");
      out.write("			            <p>Department: Cardiology</p>\r\n");
      out.write("			            <p>Role: Professor</p>\r\n");
      out.write("			            <a style=\"background-color: #0bb288; color: white;\" href=\"./LogInPage.jsp\" class=\"btn\">Make Appointment</a>\r\n");
      out.write("			        </div>\r\n");
      out.write("			        <img class=\"user-img\" src=\"./assets/image/doctorProfile/maleDr.png\" alt=\"Doctor Image\" />\r\n");
      out.write("			    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("			    <div class=\"doctor-card\">\r\n");
      out.write("			        <div class=\"doctor-card-content\">\r\n");
      out.write("			            <span class=\"doctor-card-tag\">&#8226; Real-time Booking</span>\r\n");
      out.write("			            <span class=\"doctor-card-tag\">&#8226; Fitfinity</span>\r\n");
      out.write("			            <h3> Dr. Daw Sandar </h3>\r\n");
      out.write("			            <p>Email: sandar@gmail.com</p>\r\n");
      out.write("			            <p>Tel: 09253376686</p>\r\n");
      out.write("			            <p>Department: Dermatology</p>\r\n");
      out.write("			            <p>Role: Professor</p>\r\n");
      out.write("			            <a style=\"background-color: #0bb288; color: white;\" href=\"./LogInPage.jsp\" class=\"btn\">Make Appointment</a>\r\n");
      out.write("			        </div>\r\n");
      out.write("			        <img class=\"user-img\" src=\"./assets/image/doctorProfile/femaleDr.png\" alt=\"Doctor Image\" />\r\n");
      out.write("			    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("			    <div class=\"doctor-card\">\r\n");
      out.write("			        <div class=\"doctor-card-content\">\r\n");
      out.write("			            <span class=\"doctor-card-tag\">&#8226; Real-time Booking</span>\r\n");
      out.write("			            <span class=\"doctor-card-tag\">&#8226; Fitfinity</span>\r\n");
      out.write("			            <h3> Dr. U Maung Khaing</h3>\r\n");
      out.write("			            <p>Email: maungmaungkhaing@gmail.com</p>\r\n");
      out.write("			            <p>Tel: 09250899699</p>\r\n");
      out.write("			            <p>Department: Otolaryngology</p>\r\n");
      out.write("			            <p>Role: Professor</p>\r\n");
      out.write("			            <a style=\"background-color: #0bb288; color: white;\" href=\"./LogInPage.jsp\" class=\"btn\">Make Appointment</a>\r\n");
      out.write("			        </div>\r\n");
      out.write("			        <img class=\"user-img\" src=\"./assets/image/doctorProfile/maleDr.png\" alt=\"Doctor Image\" />\r\n");
      out.write("			    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("			    <div class=\"doctor-card\">\r\n");
      out.write("			        <div class=\"doctor-card-content\">\r\n");
      out.write("			            <span class=\"doctor-card-tag\">&#8226; Real-time Booking</span>\r\n");
      out.write("			            <span class=\"doctor-card-tag\">&#8226; Fitfinity</span>\r\n");
      out.write("			            <h3> Dr. U Kyaw Zaw </h3>\r\n");
      out.write("			            <p>Email:  kyawzaw@gmail.com</p>\r\n");
      out.write("			            <p>Tel: 09971100594</p>\r\n");
      out.write("			            <p>Department: Emergency</p>\r\n");
      out.write("			            <p>Role: Professor</p>\r\n");
      out.write("			            <a style=\"background-color: #0bb288; color: white;\" href=\"./LogInPage.jsp\" class=\"btn\">Make Appointment</a>\r\n");
      out.write("			        </div>\r\n");
      out.write("			        <img class=\"user-img\" src=\"./assets/image/doctorProfile/maleDr.png\" alt=\"Doctor Image\" />\r\n");
      out.write("			    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("  $(document).ready(function(){\r\n");
      out.write("      // Load departments dropdown\r\n");
      out.write("      $.ajax({\r\n");
      out.write("          url: \"DepartmentServlet\",\r\n");
      out.write("          method: \"GET\",\r\n");
      out.write("          success: function(data) {\r\n");
      out.write("              $(\".drdrop\").html(data);\r\n");
      out.write("          }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      // Load doctors list based on selected department\r\n");
      out.write("      $(\".drdrop\").on(\"click\", \".dropdown-item\", function() {\r\n");
      out.write("          var departmentId = $(this).data(\"deptid\");\r\n");
      out.write("          $.ajax({\r\n");
      out.write("        	  url: \"GuestDoctorServlet\",\r\n");
      out.write("              method: \"GET\",\r\n");
      out.write("              data: { deptid: departmentId, patientID:\"");
      out.print( request.getParameter("PatientID"));
      out.write("\" },\r\n");
      out.write("              success: function(data) {\r\n");
      out.write("                  $(\"#doctorList\").html(data);\r\n");
      out.write("              }\r\n");
      out.write("          });\r\n");
      out.write("      });\r\n");
      out.write("   	\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
