/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-03 10:29:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LogInPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"icon\" href=\"./assets/image/logo/logo.svg\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\" integrity=\"sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"./assets/css/signInCSS.css\">\r\n");
      out.write("    <title> Fitfinity | Log In </title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!----------------------- Main Container -------------------------->\r\n");
      out.write("\r\n");
      out.write("     <div class=\"container d-flex justify-content-center align-items-center min-vh-100\">\r\n");
      out.write("\r\n");
      out.write("    <!----------------------- Login Container -------------------------->\r\n");
      out.write("\r\n");
      out.write("       <div class=\"row border rounded-5 p-3 bg-white shadow box-area\">\r\n");
      out.write("\r\n");
      out.write("    <!--------------------------- Left Box ----------------------------->\r\n");
      out.write("\r\n");
      out.write("       <div class=\"col-md-5 rounded-4 d-flex justify-content-center align-items-center flex-column left-box\" style=\"background: #0bb288;\">\r\n");
      out.write("           <div class=\"featured-image mb-3\">\r\n");
      out.write("            <img src=\"./assets/image/LoginPage/loginLogo.png\" class=\"img-fluid\" style=\"width: 500px; background-color: #0bb288;\">\r\n");
      out.write("           </div>\r\n");
      out.write("           <p class=\"text-white fs-2\" style=\"font-family: 'Courier New', Courier, monospace; font-weight: 600;\">Be Verified</p>\r\n");
      out.write("           <small class=\"text-white text-wrap text-center\" style=\"width: 17rem;font-family: 'Courier New', Courier, monospace;\">Join experienced for Infinity Healthcare</small>\r\n");
      out.write("       </div> \r\n");
      out.write("\r\n");
      out.write("    <!-------------------- ------ Right Box ---------------------------->\r\n");
      out.write("        \r\n");
      out.write("       <div class=\"col-md-7 right-box\">\r\n");
      out.write("          <div class=\"row align-items-center\">\r\n");
      out.write("          <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/SignINServlet\" method=\"post\">\r\n");
      out.write("                <div class=\"header-text mb-4\">\r\n");
      out.write("                     <h2>Hello, Again</h2>\r\n");
      out.write("                     <p>We are happy to have you back.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("               \r\n");
      out.write("                <div class=\"input-group mb-3\">\r\n");
      out.write("                    <input type=\"text\" name=\"loginEmail\" class=\"form-control form-control-lg bg-light fs-6\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.loginEmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Email address\">\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 String message = (String) request.getAttribute("message3");
        		   	   if (message!= null)
        		   	   {
        		   
      out.write("\r\n");
      out.write("        		   \r\n");
      out.write("        		   <div class=\"error-message\"> ");
      out.print( message );
      out.write(" </div> \r\n");
      out.write("        		   ");
 } 
      out.write("\r\n");
      out.write("        		   \r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <br>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"input-group mb-1\">\r\n");
      out.write("                    <input type=\"password\" name=\"loginPwd\" class=\"form-control form-control-lg bg-light fs-6\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.loginPwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Password\">\r\n");
      out.write("                    \r\n");
      out.write("                    ");
 String message2 = (String) request.getAttribute("message2");
        		   	   if (message2!= null)
        		   	   {
        		   
      out.write("\r\n");
      out.write("        		   \r\n");
      out.write("        		   <div class=\"error-message\"> ");
      out.print( message2 );
      out.write(" </div> \r\n");
      out.write("        		   ");
 } 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <br>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"input-group mb-3\">\r\n");
      out.write("				    <select name=\"userRole\" class=\"form-select form-select-lg bg-light fs-6\">\r\n");
      out.write("				    	<option value=\"\" disabled selected=\"hidden\"> Who you are... </option>\r\n");
      out.write("				        <option value=\"Patient\">Patient</option>\r\n");
      out.write("				        <option value=\"Doctor\">Doctor</option>\r\n");
      out.write("				        <option value=\"Admin\">Admin</option>\r\n");
      out.write("				    </select>\r\n");
      out.write("				</div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"input-group mb-5 d-flex justify-content-between\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div  class=\"input-group mb-3\">\r\n");
      out.write("                    <button style=\" background-color: #0bb288; color: white;\" class=\"btn btn-lg w-100 fs-6\">Login</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("                <!-- Removed form tags around this anchor tag -->\r\n");
      out.write("                <div class=\"input-group mb-3\">\r\n");
      out.write("                    <a class=\" w-100\" href=\"./guestDashboard.jsp\">\r\n");
      out.write("                        <button class=\"btn btn-lg btn-light w-100 fs-6\"><i class=\"fa-solid fa-user-large\"></i><small>Sign In as Guest</small></button>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <small>Don't have account? <a href=\"./register.jsp\">Sign Up</a></small>\r\n");
      out.write("                </div>\r\n");
      out.write("          </div>\r\n");
      out.write("       </div> \r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
