/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.85
 * Generated at: 2024-03-03 11:34:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>Form Validation</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n");
      out.write("<link rel=\"icon\" href=\"./image/logo.png\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css\">\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\" />\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("	padding: 0;\r\n");
      out.write("	margin: 0;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	font-family: \"Poppins\", sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background: rgb(53,117,254);\r\n");
      out.write("	background: linear-gradient(180deg, #0bb288 0%, #0bb288 0%, white 100%);    \r\n");
      out.write("	background-size: cover;\r\n");
      out.write("    background-position: center;\r\n");
      out.write("    background-attachment: fixed;\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	width: 90vw;\r\n");
      out.write("	max-width: 600px;\r\n");
      out.write("	padding: 2em 1.5em;\r\n");
      out.write("	background-color: #ffffff;\r\n");
      out.write("	margin: 70px auto;\r\n");
      out.write("	border-radius: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4 {\r\n");
      out.write("	font-size: 1.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".button-container {\r\n");
      out.write("    /* display: flex; */\r\n");
      out.write("    justify-content: center;\r\n");
      out.write("    margin-top: 0.2em;\r\n");
      out.write("    padding: 0 5em;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  .button-container button {\r\n");
      out.write("    \r\n");
      out.write("    padding: 0.7em 1.5em;\r\n");
      out.write("    border: none;\r\n");
      out.write("    color: #ffffff;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    box-shadow: 5px 25px 27px rgba(0, 0, 0, 0.1);\r\n");
      out.write("    text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  a{\r\n");
      out.write("  	text-align: center;\r\n");
      out.write("  	justify-content: center;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .button-container #back-button {\r\n");
      out.write("    background-color: #0bb288;\r\n");
      out.write("    border-radius: 30px;\r\n");
      out.write("    margin-right: 5.5em;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  .button-container #signup-button {\r\n");
      out.write("    background-color: #0bb288;\r\n");
      out.write("    border-radius: 30px;\r\n");
      out.write("    margin-left: 5.5em;\r\n");
      out.write("    \r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write(".input-section {\r\n");
      out.write("	margin: 0.5em 1.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label, .error-message {\r\n");
      out.write("	display: block;\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label {\r\n");
      out.write("	margin-bottom: 0.5em;\r\n");
      out.write("	font-weight: 500;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error-message {\r\n");
      out.write("	margin-top: 0.2em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input, button, select {\r\n");
      out.write("	display: block;\r\n");
      out.write("	outline: none;\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	padding: 0.5em;\r\n");
      out.write("	border-radius: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("	padding: 1em 0.5em;\r\n");
      out.write("	border: 1.5px solid #dOdOdO;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	padding: 1em 1.5em;\r\n");
      out.write("	border: 1.5px solid #d0d0d0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input[type=\"radio\"] {\r\n");
      out.write("	width: fit-content;\r\n");
      out.write("	margin-right: 0.5em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	font-size: 1em;\r\n");
      out.write("	background-color: #0bb288;\r\n");
      out.write("	border: none;\r\n");
      out.write("	color: #ffffff;\r\n");
      out.write("	padding: 0.8em 0;\r\n");
      out.write("	margin-top: 2em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".required-color {\r\n");
      out.write("	color: #ff4747;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error {\r\n");
      out.write("	border-color: #ff4747;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".valid {\r\n");
      out.write("	border-color: #37a137;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".hide {\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media only screen and (max-width: 450px) {\r\n");
      out.write("	.container {\r\n");
      out.write("		font-size: 14px;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".error-message {\r\n");
      out.write("            color: red;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write(".radio-group {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    margin-top: 0.5em;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  .radio-label {\r\n");
      out.write("    margin-right: 1em;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  .radio-label input {\r\n");
      out.write("    margin-right: 0.5em;\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write(".nrc-section {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nrc-grid {\r\n");
      out.write("    display: grid;\r\n");
      out.write("    grid-template-columns: repeat(4, 1fr);\r\n");
      out.write("    gap: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nrc-dropdown,\r\n");
      out.write("#patientNRC {\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 0.5em;\r\n");
      out.write("    border-radius: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("    <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/SignUPServlet\" method=\"post\">\r\n");
      out.write("        <h4>Create User Account</h4>\r\n");
      out.write("		\r\n");
      out.write("<!-- Name -->\r\n");
      out.write("		<div class=\"input-section\">\r\n");
      out.write("          <label>\r\n");
      out.write("            	<i class=\"fa-solid fa-id-card-clip\" style=\"color: #0bb288;\"></i> Name <span class=\"required-color\">*</span>\r\n");
      out.write("          </label>\r\n");
      out.write("          <input type=\"text\" placeholder=\"Enter your name\" name=\"patientName\" id=\"patientName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.patientName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("        \r\n");
      out.write("        ");
 String error1 = (String) request.getAttribute("message1"); 
			if(error1!=null)
			{
		
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<span class=\"error-message\"> ");
      out.print( error1 );
      out.write("  </span> <br>\r\n");
      out.write("			");
 } else { 
      out.write("\r\n");
      out.write("		        <br>\r\n");
      out.write("		    ");
 } 
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("        \r\n");
      out.write("<!-- Email --> \r\n");
      out.write("		<div class=\"input-section\"> \r\n");
      out.write("          <label>\r\n");
      out.write("            	<i class=\"fa-regular fa-envelope\" style=\"color: #0bb288;\"></i> Email <span class=\"required-color\">*</span>\r\n");
      out.write("          </label>\r\n");
      out.write("          <input type=\"text\" placeholder=\"Enter your email\" name=\"patientEmail\" id=\"patientEmail\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.patientEmail}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("          ");
 String error2 = (String) request.getAttribute("message2"); 
			if(error2!=null)
			{
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<span class=\"error-message\"> ");
      out.print( error2 );
      out.write("  </span> <br>\r\n");
      out.write("			");
 } else { 
      out.write("\r\n");
      out.write("		        <br>\r\n");
      out.write("		    ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("		\r\n");
      out.write("<!-- NRC -->\r\n");
      out.write("        <div class=\"input-section\">\r\n");
      out.write("    <label>\r\n");
      out.write("        <i class=\"fa-regular fa-address-card\" style=\"color: #0bb288;\"></i> NRC Card Number <span class=\"required-color\">*</span>\r\n");
      out.write("    </label>\r\n");
      out.write("    <div class=\"nrc-grid\">\r\n");
      out.write("    \r\n");
      out.write("	  <select id=\"firstSelect\" name=\"state\" onchange=\"updateSecondSelect()\" class=\"nrc-dropdown\">\r\n");
      out.write("	    <option value=\"1\">1</option>\r\n");
      out.write("	    <option value=\"2\">2</option>\r\n");
      out.write("	    <option value=\"3\">3</option>\r\n");
      out.write("	    <option value=\"4\">4</option>\r\n");
      out.write("	    <option value=\"5\">5</option>\r\n");
      out.write("	    <option value=\"6\">6</option>\r\n");
      out.write("	    <option value=\"7\">7</option>\r\n");
      out.write("	    <option value=\"8\">8</option>\r\n");
      out.write("	    <option value=\"9\">9</option>\r\n");
      out.write("	    <option value=\"10\">10</option>\r\n");
      out.write("	    <option value=\"11\">11</option>\r\n");
      out.write("	    <option value=\"12\">12</option>\r\n");
      out.write("	    <option value=\"13\">13</option>\r\n");
      out.write("	    <option value=\"14\">14</option>\r\n");
      out.write("	  </select>\r\n");
      out.write("	\r\n");
      out.write("	  \r\n");
      out.write("	  <select id=\"secondSelect\" name=\"city\" class=\"nrc-dropdown\">\r\n");
      out.write("	    \r\n");
      out.write("	    <!-- Options will be dynamically added here -->\r\n");
      out.write("	  </select>\r\n");
      out.write("	  \r\n");
      out.write("	  <select id=\"thirdSelect\" name=\"citizen\" class=\"nrc-dropdown\">\r\n");
      out.write("	    <option value=\"(C)\">(C)</option>\r\n");
      out.write("	    <option value=\"(A)\">(A)</option>\r\n");
      out.write("	    <option value=\"(N)\">(N)</option>\r\n");
      out.write("	  </select>\r\n");
      out.write("	  \r\n");
      out.write("	  <input type=\"text\" placeholder=\"NRC number\" name=\"number\" id=\"patientNRC\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.patientNRC}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  \r\n");
      out.write("	  <script src=\"./NRC.js\"></script>\r\n");
      out.write("	  <br>\r\n");
      out.write("	  ");
 String error3 = (String) request.getAttribute("message3"); 
			if(error3!=null)
			{
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<span class=\"error-message\"> ");
      out.print( error3 );
      out.write("  </span> <br>\r\n");
      out.write("			");
 } else { 
      out.write("\r\n");
      out.write("		        <br>\r\n");
      out.write("		    ");
 } 
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("<!-- Date Of Birth -->\r\n");
      out.write("        <div class=\"input-section\">\r\n");
      out.write("            <label>\r\n");
      out.write("            	<i class=\"fa-solid fa-calendar-days\" style=\"color: #0bb288;\"></i> Date Of Birth <span class=\"required-color\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <div style=\"position: relative;\">\r\n");
      out.write("            <input type=\"date\" min=\"1943-1-1\" max=\"2008-12-31\" name=\"patientDOB\" id=\"patientDOB\" style=\"padding: 0.5em; border-radius: 30px; width: 100%; border: 1.5px solid #d0d0d0;\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.patientDOB}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("        	</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <br>\r\n");
      out.write("		    \r\n");
      out.write("<!-- Phone -->\r\n");
      out.write("        <div class=\"input-section\">\r\n");
      out.write("            <label>\r\n");
      out.write("            	<i class=\"fa-solid fa-phone\" style=\"color: #0bb288;\"></i> Phone Number <span class=\"required-color\">*</span>\r\n");
      out.write("            </label>\r\n");
      out.write("            <input type=\"text\" name=\"patientTel\" id=\"pstientTel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.patientTel}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  placeholder=\"Enter doctor's phone: 09\">\r\n");
      out.write("            \r\n");
      out.write("            ");
 String error5 = (String) request.getAttribute("message4"); 
				if(error5!=null)
				{
			
      out.write("\r\n");
      out.write("			\r\n");
      out.write("			<span class=\"error-message\"> ");
      out.print( error5 );
      out.write("  </span> <br>\r\n");
      out.write("			");
 } else { 
      out.write("\r\n");
      out.write("		        <br>\r\n");
      out.write("		    ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("<!-- Password -->\r\n");
      out.write("		<div class=\"input-section\"> \r\n");
      out.write("          <label>\r\n");
      out.write("            	<i class=\"fa-solid fa-lock\" style=\"color: #0bb288;\"></i> Password <span class=\"required-color\">*</span>\r\n");
      out.write("          </label>\r\n");
      out.write("          <input type=\"password\"  placeholder=\"Enter a Password\" id=\"patientPwd\" name=\"patientPwd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.patientPwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("          <h5> Password must include at least one capital letter, one small letter, one number, and one special character\" name=\"patientPwd </h5>\r\n");
      out.write("          \r\n");
      out.write("         ");
 String error6 = (String) request.getAttribute("message5"); 
			if(error6!=null)
			{
		 
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<span class=\"error-message\"> ");
      out.print( error6 );
      out.write("  </span> <br>\r\n");
      out.write("			");
 } else { 
      out.write("\r\n");
      out.write("		        <br>\r\n");
      out.write("		    ");
 } 
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("		\r\n");
      out.write("<!-- Confirm Password -->\r\n");
      out.write("		<div class=\"input-section\"> \r\n");
      out.write("          <label>\r\n");
      out.write("            	<i class=\"fa-solid fa-key\" style=\"color: #0bb288;\"></i> Confirm Password <span class=\"required-color\">*</span>\r\n");
      out.write("          </label>\r\n");
      out.write("          <input type=\"password\" placeholder=\"Confirm Your Password\" name=\"confPwd\" id=\"confPwd\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.confPwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("          \r\n");
      out.write("          ");
 String error7 = (String) request.getAttribute("message6"); 
			if(error7!=null)
			{
		  
      out.write("\r\n");
      out.write("			\r\n");
      out.write("		  <span class=\"error-message\"> ");
      out.print( error7 );
      out.write("  </span> <br>\r\n");
      out.write("		  ");
 } else { 
      out.write("\r\n");
      out.write("	         <br>\r\n");
      out.write("	  	  ");
 } 
      out.write("\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("<!-- BloodType -->\r\n");
      out.write("        <div class=\"input-section\"> \r\n");
      out.write("          <label>\r\n");
      out.write("            	<i class=\"fa-solid fa-droplet\" style=\"color: #0bb288;\"></i> Blood Type <span class=\"required-color\">*</span>\r\n");
      out.write("          </label>\r\n");
      out.write("          <label for=\"bloodType\">Select Blood Type:</label>\r\n");
      out.write("		    <select id=\"bloodType\" name=\"bloodType\">\r\n");
      out.write("		        <option value=\"A\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.bloodType == 'A' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">A</option>\r\n");
      out.write("			    <option value=\"B\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.bloodType == 'B' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">B</option>\r\n");
      out.write("			    <option value=\"AB\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.bloodType == 'AB' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">AB</option>\r\n");
      out.write("			    <option value=\"O\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.bloodType == 'O' ? 'selected' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">O</option>\r\n");
      out.write("		    </select>\r\n");
      out.write("          \r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("<!-- Gender -->\r\n");
      out.write("\r\n");
      out.write("			<div class=\"input-section\">\r\n");
      out.write("				<label> <i class=\"fa-solid fa-venus-mars\"\r\n");
      out.write("					style=\"color: #0bb288;\"></i> Gender <span class=\"required-color\" >*</span>\r\n");
      out.write("				</label>\r\n");
      out.write("				<div class=\"radio-group\">\r\n");
      out.write("					<label class=\"radio-label\"> \r\n");
      out.write("						<input type=\"radio\" name=\"gender\" value=\"Male\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.gender == 'Male' ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" required > Male\r\n");
      out.write("					</label> \r\n");
      out.write("					<label class=\"radio-label\"> \r\n");
      out.write("						<input type=\"radio\" name=\"gender\" value=\"Female\"  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.gender == 'Male' ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" required> Female\r\n");
      out.write("					</label>\r\n");
      out.write("					<label class=\"radio-label\"> \r\n");
      out.write("						<input type=\"radio\" name=\"gender\" value=\"Other\"  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.gender == 'Male' ? 'checked' : ''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" required> Other\r\n");
      out.write("					</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				");
 String error9 = (String) request.getAttribute("message7");
				   if (error9 != null) {
				
      out.write("\r\n");
      out.write("				<span class=\"error-message\"> ");
      out.print(error9);
      out.write(" </span> <br>\r\n");
      out.write("				");
 } else { 
      out.write(" <br>\r\n");
      out.write("				");
 } 
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"button-container\">\r\n");
      out.write("        <button id=\"back-button\">\r\n");
      out.write("        	<a style=\"padding-left: 45%; padding-right: 45%; padding-top: 2%; padding-bottom: 2%; text-decoration: none; color: #ffffff;\" href=\"\"> Back </a>\r\n");
      out.write("        </button>\r\n");
      out.write("        <button id=\"submit-button\" class=\"btn btn-primary\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\"> Signup </button>\r\n");
      out.write("       </div>\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("		    <h3 style='color:green'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h3>\r\n");
      out.write("		    <c:remove var=\"message\"/>\r\n");
      out.write("	</c:if>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
